### ISSUE TITLE
Can not understand clean data.csv file

### ISSUE THREAD

**Issue by awalece04ku** [hemanth-kotagiri/COVID-19#1]
Dear @hemanth-kotagiri 

first of all many thanks for the file. However, I cannot understand clean data.csv file. Which column should be a label?
In the confirm column all data is one, therefore how can I use this for ML or DL?
Could you kindly explain and share one example code. 
Many thanks in advance.

**Comment by hemanth-kotagiri** [comment]
Hello @awalece04ku,
I am sorry to tell you that the data that you are referring to is pre-processed which actually doesn't have a target variable. That data is to be reviewed by a medical professional to ascertain the symptoms. Rather, you are free to use the other available datasets, please ignore the confirm column which is not true for the symptoms provided. The other dataset, such as the covid19-symptoms-dataset.csv is very low in data points. But, you can train some basic models upon the data given the fact that most likely your model will overfit it. I've been searching for a labeled public dataset for COVID-19 but I am just not finding it. Please ignore it and feel free to use others.
Thanks!

**Comment by hemanth-kotagiri** [comment]
@awalece04ku,
Also, refer to my symptoms_assessment_predicts.py file for the example code that you are seeking.

**Comment by awalece04ku** [comment]
thanks for your very quick response @hemanth-kotagiri 
I am looking such a file. If you find, kindly inform me.
Thanks in advance.

**Comment by hemanth-kotagiri** [comment]
Sure @awalece04ku will do the same. Thanks for showing interest!

**Comment by hemanth-kotagiri** [comment]
Hello @awalece04ku, 
I've had a search over the internet and found some good datasets to practice Deep Learning. I've added them to the repo. Feel free to check it out.
